version: "3.7"
services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PORT=8000
    depends_on:
      - database
    networks:
      - default
    ports:
    - "8000:8000"
volumes:
  data: